[phases.setup]
nixPkgs = ["python313"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = [
  "python backend/manage.py collectstatic --noinput"
]

[start]
cmd = "cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
