[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = [
  "cd backend && python manage.py collectstatic --noinput --clear"
]

[start]
cmd = "cd backend && python manage.py migrate --noinput && gunicorn config.wsgi:application"